version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../:/var/www/html
    depends_on:
      - app
    networks:
      - network

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: always
    networks:
      - network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - network

  app:
    build: .
    container_name: app
    volumes:
      - ../:/var/www/html
    ports:
      - "9000"
    depends_on:
      - mysql
    networks:
      - network

volumes:
  mysql_data:

networks:
  network:
